# -*- coding: utf-8 -*-
"""Projeto1corrigido.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s0OxtXjcnlaaIjBjbuL85Rg-N-XxMt9q
"""

while True:
  operacao = input("Digite a operação (soma, subtração, multiplicação, divisão): ")

  if operacao in ["soma", "subtração", "multiplicação", "divisão"]:
    num1 = float(input("Digite o primeiro número: "))
    num2 = float(input("Digite o segundo número: "))

    if operacao == "soma":
      print("A soma dos números é:", num1 + num2)
    elif operacao == "subtração":
      print("A subtração dos números é:", num1 - num2)
    elif operacao == "multiplicação":
      print("A multiplicação dos números é", num1 * num2)
    elif operacao == "divisão":
      if num2 != 0:
        print("A divisão dos números é:", num1 /num2)
      else:
        print("Erro: Divisão por zero não é permitida.")
    else:
      print("Operação inválida.")

    resposta = input("Continuar? SIM ou NAO: ").strip().upper()
  if resposta == "NAO":
      break
